export const PRISMA_ERROR_MAP: Record<string, string> = {
  // Common
  P1000: "Authentication failed against database server. Invalid database credentials.",
  P1001: "Can't reach database server. Make sure your database server is running.",
  P1002: "Database server was reached but timed out. Please try again.",
  P1003: "Database does not exist.",
  P1008: "Operations timed out.",
  P1009: "Database already exists on the database server.",
  P1010: "User was denied access on the database.",
  P1011: "Error opening a TLS connection.",
  P1012: "Schema error — invalid argument, attribute, or configuration.",
  P1013: "The provided database string is invalid.",
  P1014: "The underlying model does not exist.",
  P1015: "Prisma schema uses features not supported by the database version.",
  P1016: "Raw query had an incorrect number of parameters.",
  P1017: "Server has closed the connection.",

  // Query Engine
  P2000: "The provided value for the column is too long for the column's type.",
  P2001: "The record searched for in the where condition does not exist.",
  P2002: "Unique constraint failed.",
  P2003: "Foreign key constraint failed.",
  P2004: "A constraint failed on the database.",
  P2005: "The value stored in the database is invalid for the field's type.",
  P2006: "The provided value for the field is not valid.",
  P2007: "Data validation error.",
  P2008: "Failed to parse the query.",
  P2009: "Failed to validate the query.",
  P2010: "Raw query failed.",
  P2011: "Null constraint violation.",
  P2012: "Missing a required value.",
  P2013: "Missing the required argument for field.",
  P2014: "The change would violate a required relation between models.",
  P2015: "A related record could not be found.",
  P2016: "Query interpretation error.",
  P2017: "The records for relation between models are not connected.",
  P2018: "The required connected records were not found.",
  P2019: "Input error.",
  P2020: "Value out of range for the type.",
  P2021: "The table does not exist in the current database.",
  P2022: "The column does not exist in the current database.",
  P2023: "Inconsistent column data.",
  P2024: "Timed out fetching a new connection from the connection pool.",
  P2025: "An operation failed because required records were not found.",
  P2026: "The current database provider doesn't support a feature used in the query.",
  P2027: "Multiple errors occurred on the database during query execution.",
  P2028: "Transaction API error.",
  P2029: "Query parameter limit exceeded.",
  P2030: "Cannot find a fulltext index to use for the search.",
  P2031: "Prisma needs MongoDB to be run as a replica set for transactions.",
  P2033: "A number used in the query does not fit into a 64 bit signed integer.",
  P2034: "Transaction failed due to a write conflict or a deadlock. Please retry.",
  P2035: "Assertion violation on the database.",
  P2036: "Error in external connector.",
  P2037: "Too many database connections opened.",

  // Prisma Migrate
  P3000: "Failed to create database.",
  P3001: "Migration possible with destructive changes and possible data loss.",
  P3002: "The attempted migration was rolled back.",
  P3003: "The format of migrations changed — saved migrations are no longer valid.",
  P3004: "System database should not be altered with prisma migrate.",
  P3005: "The database schema is not empty.",
  P3006: "Migration failed to apply cleanly to the shadow database.",
  P3007: "Some requested preview features are not yet allowed in schema engine.",
  P3008: "The migration is already recorded as applied in the database.",
  P3009: "Failed migrations found — new migrations will not be applied.",
  P3010: "The name of the migration is too long (max 200 characters).",
  P3011: "Migration cannot be rolled back because it was never applied.",
  P3012: "Migration cannot be rolled back because it is not in a failed state.",
  P3013: "Datasource provider arrays are no longer supported in migrate.",
  P3014: "Prisma Migrate could not create the shadow database.",
  P3015: "Could not find the migration file.",
  P3016: "The fallback method for database resets failed.",
  P3017: "The migration could not be found.",
  P3018: "A migration failed to apply. Resolve the error before applying new migrations.",
  P3019: "Datasource provider in schema does not match migration_lock.toml.",
  P3020: "Automatic creation of shadow databases is disabled on Azure SQL.",
  P3021: "Foreign keys cannot be created on this database.",
  P3022: "Direct execution of DDL SQL statements is disabled on this database.",
  P3023: "externalTables & externalEnums must contain fully qualified identifiers.",
  P3024: "externalTables & externalEnums must contain simple identifiers without schema name.",

  // prisma db pull
  P4000: "Introspection operation failed to produce a schema file.",
  P4001: "The introspected database was empty.",
  P4002: "The schema of the introspected database was inconsistent.",

  // Prisma Accelerate
  P5011: "Too many requests — request volume exceeded. Implement back-off and retry.",
  P6000: "Accelerate server error.",
  P6001: "Invalid data source URL — must use the prisma:// protocol.",
  P6002: "Unauthorized — the API key in the connection string is invalid.",
  P6003: "Plan limit reached — included usage of the current free plan exceeded.",
  P6004: "Accelerate query timeout exceeded.",
  P6005: "Invalid parameters supplied.",
  P6006: "Prisma version is not compatible with Accelerate.",
  P6008: "Accelerate engine failed to start or could not connect to the database.",
  P6009: "Accelerate response size limit exceeded.",
  P6010: "Accelerate project is disabled. Please re-enable it.",
};

// Helper to get a human-readable message from a Prisma error
export const getPrismaErrorMessage = (code: string): string =>
  PRISMA_ERROR_MAP[code] ?? "An unexpected database error occurred.";